server:
  port: 10010
spring:
  application:
    name: JdGateway
eureka:
  instance:
    hostname: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka